version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db
      
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=tenantadmin
      - POSTGRES_PASSWORD=admin@123
      - POSTGRES_DB=multitenant

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data: