version: '3.8'

services:
  web:
    build:
      context: .
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
      - ./survey/import/:/usr/src/app/survey/import/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
      
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=multitenantadmin
      - POSTGRES_PASSWORD=admin@123
      - POSTGRES_DB=multitenant

volumes:
  postgres_data: