# Generated by Django 4.2.6 on 2023-11-30 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_alter_employee_company_alter_employee_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='role',
            field=models.CharField(choices=[('o', 'Open'), ('c', 'Close')], default='user', max_length=220),
        ),
    ]
