# Generated by Django 4.2.6 on 2023-11-30 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_authuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('dashboard', 'Dashboard')], default='user', max_length=220),
        ),
    ]
