# Generated by Django 4.2.6 on 2023-12-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_alter_authuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='has_cords',
            field=models.BooleanField(default=False),
        ),
    ]
