# Generated by Django 4.2.6 on 2023-12-01 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_question_has_cords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='has_cords',
        ),
        migrations.AddField(
            model_name='tenant',
            name='has_cords',
            field=models.BooleanField(default=False),
        ),
    ]
