# Generated by Django 4.2.6 on 2023-12-04 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_remove_question_has_cords_tenant_has_cords'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['answer'], name='survey_answ_answer_b0f4e3_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['name'], name='survey_empl_name_732ee6_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['section'], name='survey_empl_section_5504b9_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['company'], name='survey_empl_company_525890_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['employee_id'], name='survey_empl_employe_435f01_idx'),
        ),
        migrations.AddIndex(
            model_name='form',
            index=models.Index(fields=['id'], name='survey_form_id_da205e_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['text'], name='survey_ques_text_8fc8f7_idx'),
        ),
    ]
