# Generated by Django 4.2.6 on 2023-12-07 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_answer_survey_answ_answer_b0f4e3_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='dashboard',
            field=models.BooleanField(default=False),
        ),
    ]
