# Generated by Django 4.2.6 on 2023-12-09 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0009_question_dashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
