# Generated by Django 4.2.6 on 2023-12-10 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0010_tenant_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='survey.company'),
        ),
    ]
