# Generated by Django 4.2.6 on 2023-12-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0011_authuser_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='basicquestion',
            field=models.BooleanField(default=False),
        ),
    ]
