# Generated by Django 4.2.6 on 2023-12-24 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0013_employee_actual_zone_companyjson'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='company',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='division',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='job_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='section',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='questionoption',
            index=models.Index(fields=['value'], name='survey_ques_value_a90cbb_idx'),
        ),
    ]
