# Generated by Django 4.2.6 on 2023-12-17 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0018_tenant_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='slug',
        ),
    ]
