# Generated by Django 4.2.6 on 2023-12-17 18:05

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0019_remove_tenant_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='name'),
        ),
    ]
