# Generated by Django 4.2.6 on 2023-12-17 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0020_tenant_slug'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='questionoption',
            index=models.Index(fields=['value'], name='survey_ques_value_a90cbb_idx'),
        ),
    ]
