# Generated by Django 4.2.6 on 2023-12-20 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0022_alter_employee_company_alter_employee_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='survey.form'),
        ),
    ]
