# Generated by Django 4.2.6 on 2023-12-20 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0023_alter_answer_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.form'),
        ),
    ]
