# Generated by Django 4.2.6 on 2023-12-22 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0024_alter_answer_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='image_url',
            field=models.TextField(blank=True, null=True, verbose_name=''),
        ),
    ]
