# Generated by Django 4.2.6 on 2023-12-22 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0025_tenant_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
